### ISSUE TITLE
As a developer, I want to create an account lockout measure that will lock out user after multiple failed login attempts. So, possible "hacking" is avoided.

### ISSUE THREAD

**Issue by kwigs0804** [NathanielYC/CSS-AutoVault#25]
Pre-Conditions:
> User attempts to login with bad/wrong credentials

Post-Conditions:
> User account locked after three failed attempts
> User receives notification of locked out account

**Comment by md-program** [comment]
Discussed in meeting - Cognito already has built-in lockout functionality. A customizable implementation would be doable but would require significant extra work. Client said it is a low priority and not to "reinvent the wheel." Can return to this user story in the future.
